Refactor legacy design choices
 - Drop deprecated shell syntax.
 - Prefer local variables.
 - Use single quotes for patterns and expressions.
 - Make it clear that top-level scripts are shell scripts.

diff --git a/src/usr/local/bin/__vpn_manager b/src/usr/local/bin/__vpn_manager
--- a/src/usr/local/bin/__vpn_manager
+++ b/src/usr/local/bin/__vpn_manager
@@ -18,7 +18,7 @@ LOG_FILENAME="/var/log/${APP_NAME}"
 #################################################
 #            Configure notifications.           #
 #################################################
-NOTIFICATION_TITLE="`echo "${APP_NAME}" | sed "s/\\(.\\)/\\U\\1/"`"
+NOTIFICATION_TITLE="$(echo "${APP_NAME}" | sed -E 's/(.)/\U\1/')"
 NOTIFICATION_ICON_SUCCESS="dialog-positive"
 NOTIFICATION_ICON_FAILURE="dialog-error"
 NOTIFICATION_TIMEOUT=5000
@@ -110,7 +110,7 @@ download() {
 #   Writes the decoded string to stdout.
 #################################################
 urid() {
-  printf "%b" "`sed -E 's/%([a-fA-F0-9]{2})/\\\\x\\1/g'`"
+  printf "%b" "$(sed -E 's/%([a-fA-F0-9]{2})/\\\x\1/g')"
 }
 
 #################################################
@@ -125,10 +125,10 @@ urid() {
 #   otherwise, a non-zero status.
 #################################################
 send_notification() {
-  display_id="`ls /tmp/.X11-unix/X* 2> /dev/null | head -n 1 | sed "s|/tmp/.X11-unix/X||"`"
-  display=":${display_id:-0}"
-  display_user="`who | grep "(${display})\|(login screen)" | head -n 1 | sed "s/\\s.*//"`"
-  display_user_id="`id -u "${display_user}" 2> /dev/null`"
+  local display_id="$(ls /tmp/.X11-unix/X* 2> /dev/null | head -n 1 | sed -E 's|/tmp/.X11-unix/X([0-9]*).*|\1|')"
+  local display=":${display_id:-0}"
+  local display_user="$(who | grep "(${display})\|(login screen)" | head -n 1 | sed 's/\s.*//')"
+  local display_user_id="$(id -u "${display_user}" 2> /dev/null)"
 
   if command_exists notify-send; then
     sudo -u "${display_user}" \
@@ -139,7 +139,7 @@ send_notification() {
     sudo -u "${display_user}" \
       DISPLAY="${display}" \
       DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/${display_user_id}/bus \
-      kdialog --passivepopup "${2}" "`expr "${4:-3000}" / 1000`" --title "${1}" --icon "${3}"
+      kdialog --passivepopup "${2}" "$((${4:-3000} / 1000))" --title "${1}" --icon "${3}"
   else
     return 1
   fi > /dev/null 2>& 1
@@ -159,7 +159,7 @@ send_notification() {
 #   with a status of 1).
 #################################################
 assert_is_root() {
-  [ "${EUID:-"`id -u`"}" -eq 0 ] && return
+  [ "${EUID:-"$(id -u)"}" -eq 0 ] && return
 
   error "cannot query current connection status: Permission denied"
   exit 1
@@ -175,7 +175,7 @@ assert_is_root() {
 #   otherwise, a non-zero status.
 #################################################
 is_ss() {
-  echo "${1}" | grep -qE "^ss://[a-zA-Z0-9+/]+={0,3}@.+:[0-9]{1,5}(/.*)?(#.*)?$"
+  echo "${1}" | grep -qE '^ss://[a-zA-Z0-9+/]+={0,3}@.+:[0-9]{1,5}(/.*)?(#.*)?$'
 }
 
 #################################################
@@ -189,7 +189,7 @@ is_ss() {
 #   otherwise, a non-zero status.
 #################################################
 is_ss64() {
-  echo "${1}" | grep -qE "^ss://[a-zA-Z0-9+/]+={0,3}(/.*)?(#.*)?$"
+  echo "${1}" | grep -qE '^ss://[a-zA-Z0-9+/]+={0,3}(/.*)?(#.*)?$'
 }
 
 #################################################
@@ -203,7 +203,7 @@ is_ss64() {
 #   otherwise, a non-zero status.
 #################################################
 is_ssconf() {
-  echo "${1}" | grep -qE "^ssconf://.+"
+  echo "${1}" | grep -qE '^ssconf://.+'
 }
 
 #################################################
@@ -216,7 +216,7 @@ is_ssconf() {
 #   otherwise, a non-zero status.
 #################################################
 is_json() {
-  echo "${1}" | grep -qE "^\s*{"
+  echo "${1}" | grep -qE '^\s*{'
 }
 
 #################################################
@@ -244,7 +244,7 @@ is_valid_transport() {
 #   otherwise, a non-zero status.
 #################################################
 extract_key_ip() {
-  echo "`normalize_key "${1}"`" | grep -oE "@.+:[0-9]{1,5}(/|#|$)" | grep -oE "[^@]+:[0-9]+"
+  echo "$(normalize_key "${1}")" | grep -oE '@.+:[0-9]{1,5}(/|#|$)' | grep -oE '[^@]+:[0-9]+'
 }
 
 #################################################
@@ -296,7 +296,7 @@ ss642ss() {
 #   Writes the normalized static key to stdout.
 #################################################
 ssconf2ss() {
-  normalize_key "`download "\`echo "${1}" | sed "s|ssconf://|https://|"\`" 2> /dev/null`"
+  normalize_key "$(download "$(echo "${1}" | sed 's|ssconf://|https://|')" 2> /dev/null)"
 }
 
 #################################################
@@ -320,9 +320,9 @@ json2ss() {
 #   Writes the extracted key name to stdout.
 #################################################
 extract_default_key_name() {
-  normalized_key="`normalize_key "${1}"`"
-  if echo "${normalized_key}" | grep -qF "#"; then
-    echo "${normalized_key}" | sed "s/[^#]*#//" | urid
+  local normalized_key="$(normalize_key "${1}")"
+  if echo "${normalized_key}" | grep -qF '#'; then
+    echo "${normalized_key}" | sed 's/[^#]*#//' | urid
   else
     extract_key_ip "${normalized_key}"
   fi
@@ -340,7 +340,7 @@ extract_default_key_name() {
 #   otherwise, a non-zero status.
 #################################################
 extract_key_name() {
-  decode_key_name "`echo "${1}" | sed "s/=.*//"`"
+  decode_key_name "$(echo "${1}" | sed 's/=.*//')"
 }
 
 #################################################
@@ -355,7 +355,7 @@ extract_key_name() {
 #   otherwise, a non-zero status.
 #################################################
 extract_key_transport() {
-  normalize_key "`echo "${1}" | sed "s/[^=]*=//"`"
+  normalize_key "$(echo "${1}" | sed 's/[^=]*=//')"
 }
 
 #################################################
@@ -366,7 +366,7 @@ extract_key_transport() {
 #   Writes the encoded access key name to stdout.
 #################################################
 encode_key_name() {
-  echo "${1}" | sed "s/=/%20/g"
+  echo "${1}" | sed 's/=/%20/g'
 }
 
 #################################################
@@ -377,7 +377,7 @@ encode_key_name() {
 #   Writes the decoded access key name to stdout.
 #################################################
 decode_key_name() {
-  echo "${1}" | sed "s/%20/=/g"
+  echo "${1}" | sed 's/%20/=/g'
 }
 
 #################################################
@@ -396,8 +396,8 @@ decode_key_name() {
 #################################################
 format_key() {
   echo "${1}" \
-    | sed "s/%name%/`extract_key_name "${2}" | sed "s/&/\\\\\\\\&/g"`/g" \
-    | sed "s/%ip%/`extract_key_ip "\`extract_key_transport "${2}"\`"`/g" \
+    | sed "s/%name%/$(extract_key_name "${2}" | sed 's/&/\\&/g')/g" \
+    | sed "s/%ip%/$(extract_key_ip "$(extract_key_transport "${2}")")/g" \
     | sed "s/%index%/${3:-1}/g"
 }
 
@@ -415,8 +415,8 @@ get_key_index() {
   [ -f "${STORAGE_FILENAME}" ] || return 1
 
   case "${1}" in
-    ""|*[!0-9]*) sed "s/^/${SOL}/" "${STORAGE_FILENAME}" | grep -m 1 -inF "${SOL}`encode_key_name "${1}"`=" | grep -o "^[0-9]*" ;;
-    *) [ -n "`sed "${1}q;d" "${STORAGE_FILENAME}"`" ] && echo "${1}" ;;
+    ""|*[!0-9]*) sed "s/^/${SOL}/" "${STORAGE_FILENAME}" | grep -m 1 -inF "${SOL}$(encode_key_name "${1}")=" | grep -o '^[0-9]*' ;;
+    *) [ -n "$(sed "${1}q;d" "${STORAGE_FILENAME}")" ] && echo "${1}" ;;
   esac
 }
 
@@ -431,7 +431,7 @@ get_key_index() {
 #   otherwise, a non-zero status.
 #################################################
 get_key() {
-  key_index=`get_key_index "${1}"`
+  local key_index=$(get_key_index "${1}")
   [ $? -eq 0 ] && sed "${key_index}q;d" "${STORAGE_FILENAME}"
 }
 
@@ -445,13 +445,13 @@ add_key() {
   is_valid_transport "${1}" || return 1
 
   init_storage
-  new_key_name="${2:-"`extract_default_key_name "${1}"`"}"
-  existing_key_index="`get_key_index "${new_key_name}"`"
+  local new_key_name="${2:-"$(extract_default_key_name "${1}")"}"
+  local existing_key_index="$(get_key_index "${new_key_name}")"
 
   if [ -n "${existing_key_index}" ]; then
-    sed -i"" "${existing_key_index} c\\`encode_key_name "${new_key_name}"`=${1}" "${STORAGE_FILENAME}"
+    sed -i"" "${existing_key_index} c\\$(encode_key_name "${new_key_name}")=${1}" "${STORAGE_FILENAME}"
   else
-    echo "`encode_key_name "${new_key_name}"`=${1}" >> "${STORAGE_FILENAME}"
+    echo "$(encode_key_name "${new_key_name}")=${1}" >> "${STORAGE_FILENAME}"
   fi
 }
 
@@ -465,7 +465,7 @@ add_key() {
 #   otherwise, a non-zero status.
 #################################################
 remove_key() {
-  existing_key_index="`get_key_index "${1}"`"
+  local existing_key_index="$(get_key_index "${1}")"
   [ -n "${existing_key_index}" ] && sed -i"" "${existing_key_index}d" "${STORAGE_FILENAME}"
 }
 
@@ -481,11 +481,11 @@ remove_key() {
 list_keys() {
   init_storage
 
-  list_entry_pattern="${1:-"%index%${SOL}%name%${SOL}%ip%"}"
-  i=0
+  local list_entry_pattern="${1:-"%index%${SOL}%name%${SOL}%ip%"}"
+  local i=0
 
   while IFS="" read -r key_entry || [ -n "${key_entry}" ]; do
-    i=`expr ${i} + 1`
+    i=$((${i} + 1))
     format_key "${list_entry_pattern}" "${key_entry}" "${i}"
   done < "${STORAGE_FILENAME}" | ([ -z "${1}" ] && column -s "${SOL}" -t || cat -)
 }
@@ -505,8 +505,8 @@ list_keys() {
 get_status() {
   init_session
 
-  current_status_code="`grep -o "^[0-9]*" "${SESSION_FILENAME}"`"
-  current_status_arg="`sed "s/^[0-9]* //" "${SESSION_FILENAME}"`"
+  local current_status_code="$(grep -o '^[0-9]*' "${SESSION_FILENAME}")"
+  local current_status_arg="$(sed 's/^[0-9]* //' "${SESSION_FILENAME}")"
 
   case "${current_status_code}" in
     0|1|2) ;;
@@ -536,10 +536,10 @@ terminate_or_kill() {
   pkill -TERM -x "${1}"
 
   # Loop until the process is terminated or maximum attempts reached.
-  termination_attempt=0
+  local termination_attempt=0
   while pgrep -x "${1}" > /dev/null && [ "${termination_attempt}" -lt "${3:-50}" ]; do
     sleep "${2:-"0.05"}"
-    termination_attempt=`expr ${termination_attempt} + 1`
+    termination_attempt=$((${termination_attempt} + 1))
   done
 
   # If process still exists, forcefully kill it using SIGKILL.
@@ -563,9 +563,9 @@ terminate_or_kill() {
 #   otherwise, a non-zero status.
 #################################################
 disconnect() {
-  disconnection_key_name="`get_status`"
-  disconnection_status=$?
-  disconnection_key="`get_key "${disconnection_key_name}"`"
+  local disconnection_key_name; disconnection_key_name="$(get_status)"
+  local disconnection_status=$?
+  local disconnection_key="$(get_key "${disconnection_key_name}")"
   if [ -n "${1}" ] && [ "${disconnection_status}" -ne 1 ]; then
     disconnection_status=2
   else
@@ -574,7 +574,7 @@ disconnect() {
 
   terminate_or_kill __vpn_connect
 
-  echo "${disconnection_status} `extract_key_name "${disconnection_key}"`" > "${SESSION_FILENAME}"
+  echo "${disconnection_status} $(extract_key_name "${disconnection_key}")" > "${SESSION_FILENAME}"
   [ -n "${disconnection_key}" ] && format_key "${2:-"%name%"}" "${disconnection_key}"
 }
 
@@ -597,24 +597,24 @@ disconnect() {
 #   otherwise, a non-zero status.
 #################################################
 connect() {
-  connection_key_name="${1:-"`get_status`"}"
-  connection_key="`get_key "${connection_key_name:-1}"`"
+  local connection_key_name="${1:-"$(get_status)"}"
+  local connection_key="$(get_key "${connection_key_name:-1}")"
   if [ -z "${connection_key}" ]; then
     error "unknown key: ${connection_key_name}"
     return 1
   fi
 
   disconnect > /dev/null 2>& 1
-  /usr/local/bin/__vpn_connect -transport "`extract_key_transport "${connection_key}"`" > "${LOG_FILENAME}" 2>& 1 &
-  connection_id=$!
+  /usr/local/bin/__vpn_connect -transport "$(extract_key_transport "${connection_key}")" > "${LOG_FILENAME}" 2>& 1 &
+  local connection_id=$!
   sleep 1
 
   if ps -p "${connection_id}" > /dev/null 2>& 1; then
-    echo "0 `extract_key_name "${connection_key}"`" > "${SESSION_FILENAME}"
+    echo "0 $(extract_key_name "${connection_key}")" > "${SESSION_FILENAME}"
     format_key "${2:-"%name%"}" "${connection_key}"
     return 0
   else
-    error "`tail -n 1 "${LOG_FILENAME}" | sed "s/^\\[ERROR\\][ 0-9/:]*//"`"
+    error "$(tail -n 1 "${LOG_FILENAME}" | sed 's/^\[ERROR\][ 0-9/:]*//')"
     return 1
   fi
 }
@@ -663,9 +663,9 @@ execute_action() {
       ;;
 
     status)
-      current_status_name="`get_status`"
-      current_status=$?
-      current_status_key="`get_key "${current_status_name}"`"
+      local current_status_name; current_status_name="$(get_status)"
+      local current_status=$?
+      local current_status_key="$(get_key "${current_status_name}")"
 
       if [ "${current_status}" -eq 0 ] && [ -n "${current_status_key}" ]; then
         format_key "${NOTIFICATION_BODY_CONNECTED}" "${current_status_key}"
@@ -752,13 +752,13 @@ fatal_error() {
 #   ... A list of the command line arguments.
 #################################################
 main() {
-  quiet=""
-  notify=""
-  suspend=""
-  format=""
-  action=""
-  arg0=""
-  arg1=""
+  local quiet=""
+  local notify=""
+  local suspend=""
+  local format=""
+  local action=""
+  local arg0=""
+  local arg1=""
 
   # Parse the arguments and options.
   while [ -n "${1}" ]; do
@@ -832,15 +832,15 @@ main() {
   assert_is_root
 
   # Redirect the output to a variable, so we can decide how to display it later.
-  action_result="`execute_action "${action}" "${arg0:-"${format:-"${suspend}"}"}" "${arg1}" 2>& 1`"
-  action_code=$?
+  local action_result; action_result="$(execute_action "${action}" "${arg0:-"${format:-"${suspend}"}"}" "${arg1}" 2>& 1)"
+  local action_code=$?
 
   # Display the output.
   # Either via a notification if the "--notify" flag has been provided, or
   # just write it back to stdout.
   if [ -n "${action_result}" ]; then
     if [ -n "${notify}" ]; then
-      action_icon="`[ "${action_code}" -eq 0 ] && echo "${NOTIFICATION_ICON_SUCCESS}" || echo "${NOTIFICATION_ICON_FAILURE}"`"
+      local action_icon="$([ "${action_code}" -eq 0 ] && echo "${NOTIFICATION_ICON_SUCCESS}" || echo "${NOTIFICATION_ICON_FAILURE}")"
       send_notification "${NOTIFICATION_TITLE}" "${action_result}" "${action_icon}"
     elif [ -z "${quiet}" ]; then
       echo "${action_result}"
@@ -849,4 +849,4 @@ main() {
   exit "${action_code}"
 }
 
-main "$@"
+main "${@}"
